//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 09:32:48 PM EEST 
//


package ro.smc.engine.util.serialization;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ConfigurationItems"/>
 *         &lt;element ref="{}ExternalConfigurations"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="configurationName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="configurationHash" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="includesSecurity" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "configurationItems",
    "externalConfigurations"
})
@XmlRootElement(name = "ConfigurationInstance")
public class ConfigurationInstance {

    @XmlElement(name = "ConfigurationItems", required = true)
    protected ConfigurationItems configurationItems;
    @XmlElement(name = "ExternalConfigurations", required = true)
    protected ExternalConfigurations externalConfigurations;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "configurationName", required = true)
    protected String configurationName;
    @XmlAttribute(name = "configurationHash", required = true)
    protected String configurationHash;
    @XmlAttribute(name = "description", required = true)
    protected String description;
    @XmlAttribute(name = "includesSecurity", required = true)
    protected boolean includesSecurity;

    /**
     * Gets the value of the configurationItems property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationItems }
     *     
     */
    public ConfigurationItems getConfigurationItems() {
        return configurationItems;
    }

    /**
     * Sets the value of the configurationItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationItems }
     *     
     */
    public void setConfigurationItems(ConfigurationItems value) {
        this.configurationItems = value;
    }

    /**
     * Gets the value of the externalConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalConfigurations }
     *     
     */
    public ExternalConfigurations getExternalConfigurations() {
        return externalConfigurations;
    }

    /**
     * Sets the value of the externalConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalConfigurations }
     *     
     */
    public void setExternalConfigurations(ExternalConfigurations value) {
        this.externalConfigurations = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the configurationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationName() {
        return configurationName;
    }

    /**
     * Sets the value of the configurationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationName(String value) {
        this.configurationName = value;
    }

    /**
     * Gets the value of the configurationHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigurationHash() {
        return configurationHash;
    }

    /**
     * Sets the value of the configurationHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigurationHash(String value) {
        this.configurationHash = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the includesSecurity property.
     * 
     */
    public boolean isIncludesSecurity() {
        return includesSecurity;
    }

    /**
     * Sets the value of the includesSecurity property.
     * 
     */
    public void setIncludesSecurity(boolean value) {
        this.includesSecurity = value;
    }

}
