//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.23 at 09:32:48 PM EEST 
//


package ro.smc.engine.util.serialization;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.smc.engine.util.serialization package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.smc.engine.util.serialization
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExternalConfigurations }
     * 
     */
    public ExternalConfigurations createExternalConfigurations() {
        return new ExternalConfigurations();
    }

    /**
     * Create an instance of {@link ExternalConfigurationKey }
     * 
     */
    public ExternalConfigurationKey createExternalConfigurationKey() {
        return new ExternalConfigurationKey();
    }

    /**
     * Create an instance of {@link PrimaryKeys }
     * 
     */
    public PrimaryKeys createPrimaryKeys() {
        return new PrimaryKeys();
    }

    /**
     * Create an instance of {@link FieldValue }
     * 
     */
    public FieldValue createFieldValue() {
        return new FieldValue();
    }

    /**
     * Create an instance of {@link ConfigurationItems }
     * 
     */
    public ConfigurationItems createConfigurationItems() {
        return new ConfigurationItems();
    }

    /**
     * Create an instance of {@link ConfigurationDataItem }
     * 
     */
    public ConfigurationDataItem createConfigurationDataItem() {
        return new ConfigurationDataItem();
    }

    /**
     * Create an instance of {@link RootRow }
     * 
     */
    public RootRow createRootRow() {
        return new RootRow();
    }

    /**
     * Create an instance of {@link BaseRow }
     * 
     */
    public BaseRow createBaseRow() {
        return new BaseRow();
    }

    /**
     * Create an instance of {@link FragmentRows }
     * 
     */
    public FragmentRows createFragmentRows() {
        return new FragmentRows();
    }

    /**
     * Create an instance of {@link FragmentRow }
     * 
     */
    public FragmentRow createFragmentRow() {
        return new FragmentRow();
    }

    /**
     * Create an instance of {@link ConfigurationSqlItem }
     * 
     */
    public ConfigurationSqlItem createConfigurationSqlItem() {
        return new ConfigurationSqlItem();
    }

    /**
     * Create an instance of {@link ConfigurationInstance }
     * 
     */
    public ConfigurationInstance createConfigurationInstance() {
        return new ConfigurationInstance();
    }

}
