//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.30 at 10:53:23 AM EEST 
//


package ro.smc.engine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Fields" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="primaryKeyType" type="{}PrimaryKeyType" default="None" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="external" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="externalFragmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="parentRelation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="descriptionField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="activeField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ownerFragment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tableFilter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="loadFrom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beforeFragment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fields"
})
@XmlRootElement(name = "ConfigurationFragment")
public class ConfigurationFragment {

    @XmlElement(name = "Fields")
    protected Fields fields;
    @XmlAttribute(name = "primaryKeyType")
    protected PrimaryKeyType primaryKeyType;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "table")
    protected String table;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "external")
    protected Boolean external;
    @XmlAttribute(name = "externalFragmentName")
    protected String externalFragmentName;
    @XmlAttribute(name = "parentRelation")
    protected String parentRelation;
    @XmlAttribute(name = "link")
    protected String link;
    @XmlAttribute(name = "descriptionField")
    protected String descriptionField;
    @XmlAttribute(name = "activeField")
    protected String activeField;
    @XmlAttribute(name = "ownerFragment")
    protected String ownerFragment;
    @XmlAttribute(name = "tableFilter")
    protected String tableFilter;
    @XmlAttribute(name = "loadFrom")
    protected String loadFrom;
    @XmlAttribute(name = "beforeFragment")
    protected String beforeFragment;

    /**
     * Gets the value of the fields property.
     * 
     * @return
     *     possible object is
     *     {@link Fields }
     *     
     */
    public Fields getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fields }
     *     
     */
    public void setFields(Fields value) {
        this.fields = value;
    }

    /**
     * Gets the value of the primaryKeyType property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryKeyType }
     *     
     */
    public PrimaryKeyType getPrimaryKeyType() {
        if (primaryKeyType == null) {
            return PrimaryKeyType.NONE;
        } else {
            return primaryKeyType;
        }
    }

    /**
     * Sets the value of the primaryKeyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryKeyType }
     *     
     */
    public void setPrimaryKeyType(PrimaryKeyType value) {
        this.primaryKeyType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTable(String value) {
        this.table = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the external property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExternal() {
        return external;
    }

    /**
     * Sets the value of the external property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExternal(Boolean value) {
        this.external = value;
    }

    /**
     * Gets the value of the externalFragmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalFragmentName() {
        return externalFragmentName;
    }

    /**
     * Sets the value of the externalFragmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalFragmentName(String value) {
        this.externalFragmentName = value;
    }

    /**
     * Gets the value of the parentRelation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentRelation() {
        return parentRelation;
    }

    /**
     * Sets the value of the parentRelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentRelation(String value) {
        this.parentRelation = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the descriptionField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionField() {
        return descriptionField;
    }

    /**
     * Sets the value of the descriptionField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionField(String value) {
        this.descriptionField = value;
    }

    /**
     * Gets the value of the activeField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveField() {
        return activeField;
    }

    /**
     * Sets the value of the activeField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveField(String value) {
        this.activeField = value;
    }

    /**
     * Gets the value of the ownerFragment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerFragment() {
        return ownerFragment;
    }

    /**
     * Sets the value of the ownerFragment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerFragment(String value) {
        this.ownerFragment = value;
    }

    /**
     * Gets the value of the tableFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableFilter() {
        return tableFilter;
    }

    /**
     * Sets the value of the tableFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableFilter(String value) {
        this.tableFilter = value;
    }

    /**
     * Gets the value of the loadFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadFrom() {
        return loadFrom;
    }

    /**
     * Sets the value of the loadFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadFrom(String value) {
        this.loadFrom = value;
    }

    /**
     * Gets the value of the beforeFragment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeFragment() {
        return beforeFragment;
    }

    /**
     * Sets the value of the beforeFragment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeFragment(String value) {
        this.beforeFragment = value;
    }

}
