//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.30 at 10:53:23 AM EEST 
//


package ro.smc.engine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrimaryKeyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrimaryKeyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="Identity"/>
 *     &lt;enumeration value="UniqueidentifierIdentity"/>
 *     &lt;enumeration value="UserSupplied"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrimaryKeyType")
@XmlEnum
public enum PrimaryKeyType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("Identity")
    IDENTITY("Identity"),
    @XmlEnumValue("UniqueidentifierIdentity")
    UNIQUEIDENTIFIER_IDENTITY("UniqueidentifierIdentity"),
    @XmlEnumValue("UserSupplied")
    USER_SUPPLIED("UserSupplied");
    private final String value;

    PrimaryKeyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrimaryKeyType fromValue(String v) {
        for (PrimaryKeyType c: PrimaryKeyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
