//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.30 at 10:53:23 AM EEST 
//


package ro.smc.engine;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SqlObjectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SqlObjectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="StoredProcedure"/>
 *     &lt;enumeration value="View"/>
 *     &lt;enumeration value="Table"/>
 *     &lt;enumeration value="Function"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SqlObjectType")
@XmlEnum
public enum SqlObjectType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("StoredProcedure")
    STORED_PROCEDURE("StoredProcedure"),
    @XmlEnumValue("View")
    VIEW("View"),
    @XmlEnumValue("Table")
    TABLE("Table"),
    @XmlEnumValue("Function")
    FUNCTION("Function");
    private final String value;

    SqlObjectType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SqlObjectType fromValue(String v) {
        for (SqlObjectType c: SqlObjectType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
